name: final-project

services:
  mongo:
    image: mongo:8.0.6
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - final-project

  mongo-setup:
    image: mongo:8.0.6
    depends_on:
    - mongo
    command: >
      bash -c "sleep 10 &&
      mongosh --host mongo --eval 'rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongo:27017\"}]})'"
    networks:
      - final-project

  redis:
    image: redis:7.4.3
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume_data:/data
    networks:
      - final-project

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
    - "5540:5540"
    volumes:
    - redis_insight_volume_data:/db
    networks:
      - final-project

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo-setup
      - redis
      - redis_insight
    networks:
      - final-project
    ports:
      - 3055:3055

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - final-project
    ports:
      - 5173:5173
    command: npm run dev -- --host

volumes:
  mongo-data:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  final-project:
    driver: bridge